// Entity/mesh construction helpers. Unit primitives are cached and shared;
// entities scale them, so the whole campus uses only a handful of GPU
// buffers. Custom organic geometry (tree canopies) is generated by
// displacing sphere geometry on the CPU.

import * as pc from "playcanvas";

export type V3 = [number, number, number];

export class Builder {
  private meshes = new Map<string, pc.Mesh>();

  constructor(public device: pc.GraphicsDevice) {}

  unitBox(): pc.Mesh {
    return this.cached("box", () => pc.Mesh.fromGeometry(this.device, new pc.BoxGeometry()));
  }

  sphere(segments = 16): pc.Mesh {
    return this.cached(`sphere${segments}`, () =>
      pc.Mesh.fromGeometry(
        this.device,
        new pc.SphereGeometry({ radius: 0.5, latitudeBands: segments, longitudeBands: segments })
      )
    );
  }

  cylinder(capSegments = 16): pc.Mesh {
    return this.cached(`cyl${capSegments}`, () =>
      pc.Mesh.fromGeometry(
        this.device,
        new pc.CylinderGeometry({ radius: 0.5, height: 1, capSegments })
      )
    );
  }

  cone(capSegments = 16): pc.Mesh {
    return this.cached(`cone${capSegments}`, () =>
      pc.Mesh.fromGeometry(
        this.device,
        new pc.ConeGeometry({ baseRadius: 0.5, peakRadius: 0, height: 1, capSegments })
      )
    );
  }

  plane(): pc.Mesh {
    return this.cached("plane", () => pc.Mesh.fromGeometry(this.device, new pc.PlaneGeometry()));
  }

  /** Unit quad in XY plane facing +Z (for billboards/overlays). */
  quad(): pc.Mesh {
    return this.cached("quad", () => {
      const mesh = new pc.Mesh(this.device);
      mesh.setPositions([-0.5, -0.5, 0, 0.5, -0.5, 0, 0.5, 0.5, 0, -0.5, 0.5, 0]);
      mesh.setNormals([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1]);
      mesh.setUvs(0, [0, 0, 1, 0, 1, 1, 0, 1]);
      mesh.setIndices([0, 1, 2, 0, 2, 3]);
      mesh.update();
      return mesh;
    });
  }

  /** Organic canopy blob: displaced, squashed icosphere. Cached per seed. */
  canopy(seed: number): pc.Mesh {
    return this.cached(`canopy${seed % 8}`, () => {
      const geo = new pc.SphereGeometry({ radius: 0.5, latitudeBands: 10, longitudeBands: 14 });
      const p = geo.positions as number[];
      for (let i = 0; i < p.length; i += 3) {
        const x = p[i];
        const y = p[i + 1];
        const z = p[i + 2];
        const n =
          Math.sin(x * 10.2 + seed) * Math.cos(y * 8.6 + seed * 2.1) +
          Math.sin(z * 12.6 + seed * 3.7) * 0.6;
        const s = 1 + 0.13 * n;
        p[i] = x * s;
        p[i + 1] = y * s * 0.82;
        p[i + 2] = z * s;
      }
      geo.normals = pc.calculateNormals(p, geo.indices as number[]);
      return pc.Mesh.fromGeometry(this.device, geo);
    });
  }

  private cached(key: string, make: () => pc.Mesh): pc.Mesh {
    let m = this.meshes.get(key);
    if (!m) {
      m = make();
      this.meshes.set(key, m);
    }
    return m;
  }

  /** Entity holding a single mesh instance. */
  ent(
    name: string,
    mesh: pc.Mesh,
    material: pc.Material,
    o: {
      parent?: pc.Entity;
      p?: V3;
      s?: V3;
      rot?: V3;
      cast?: boolean;
      receive?: boolean;
    } = {}
  ): pc.Entity {
    const e = new pc.Entity(name);
    const mi = new pc.MeshInstance(mesh, material);
    e.addComponent("render", {
      meshInstances: [mi],
      castShadows: o.cast ?? false,
      receiveShadows: o.receive ?? true,
    });
    if (o.p) e.setLocalPosition(o.p[0], o.p[1], o.p[2]);
    if (o.rot) e.setLocalEulerAngles(o.rot[0], o.rot[1], o.rot[2]);
    if (o.s) e.setLocalScale(Math.abs(o.s[0]), Math.abs(o.s[1]), Math.abs(o.s[2]));
    o.parent?.addChild(e);
    return e;
  }

  /** Scaled unit box (the workhorse for architectural detail). */
  box(
    name: string,
    material: pc.Material,
    o: { parent?: pc.Entity; p?: V3; s?: V3; rot?: V3; cast?: boolean; receive?: boolean } = {}
  ): pc.Entity {
    return this.ent(name, this.unitBox(), material, o);
  }

  group(name: string, parent?: pc.Entity, p?: V3, rotY = 0): pc.Entity {
    const e = new pc.Entity(name);
    if (p) e.setLocalPosition(p[0], p[1], p[2]);
    if (rotY) e.setLocalEulerAngles(0, rotY, 0);
    parent?.addChild(e);
    return e;
  }

  /**
   * GPU-instanced copies of a mesh: one draw call for all transforms.
   * Returns the entity; the instance buffer is static.
   */
  instanced(
    name: string,
    mesh: pc.Mesh,
    material: pc.Material,
    transforms: { p: V3; s: V3; rotY?: number }[],
    o: { parent?: pc.Entity; cast?: boolean } = {}
  ): pc.Entity {
    const e = new pc.Entity(name);
    const mi = new pc.MeshInstance(mesh, material);
    const data = new Float32Array(transforms.length * 16);
    const m = new pc.Mat4();
    const pos = new pc.Vec3();
    const rot = new pc.Quat();
    const scl = new pc.Vec3();
    transforms.forEach((t, i) => {
      pos.set(t.p[0], t.p[1], t.p[2]);
      rot.setFromEulerAngles(0, t.rotY ?? 0, 0);
      scl.set(t.s[0], t.s[1], t.s[2]);
      m.setTRS(pos, rot, scl);
      data.set(m.data, i * 16);
    });
    const vb = new pc.VertexBuffer(
      this.device,
      pc.VertexFormat.getDefaultInstancingFormat(this.device),
      transforms.length,
      { data: data.buffer }
    );
    mi.setInstancing(vb);
    e.addComponent("render", {
      meshInstances: [mi],
      castShadows: o.cast ?? false,
      receiveShadows: true,
    });
    o.parent?.addChild(e);
    return e;
  }
}

export const rnd = (seed: number, i: number) => {
  const v = Math.sin(seed * 37.13 + i * 13.7) * 43758.5453;
  return v - Math.floor(v);
};

/** Exponential smoothing toward a target (frame-rate independent). */
export const damp = (current: number, target: number, lambda: number, dt: number) =>
  pc.math.lerp(current, target, 1 - Math.exp(-lambda * dt));
